### ISSUE TITLE
URL to download telemetry utilities needs to be corrected in setup guide

### ISSUE THREAD

**Issue by pradeepar** [dell/iDRAC-Telemetry-Reference-Tools#1]
step 2 in docker-compose-files/setup_guide.pdf refers to 
Download the telemetry utilities from - https://github.com/dell/iDRACTelemetry-Scripting

the url appears to have a typo (missing hypen) and should be corrected to https://github.com/dell/iDRAC-Telemetry-Scripting 

![image](https://user-images.githubusercontent.com/7271680/114961851-43312580-9e87-11eb-8c73-a0211d3be06d.png)

**Comment by cjmadathil** [comment]
Addressed with commit - 70e88197f164ff71f6fbe03d41838da8f7f6bf49
