### ISSUE TITLE
gafana get telemetry data from influxdb error:influxDB:Bad Request

### ISSUE THREAD

**Issue by huazhou007** [dell/iDRAC-Telemetry-Reference-Tools#108]
gafana get telemetry data from influxdb error:influxDB:Bad Request
SO influxdb username and password is?   Could you tell me!

![image](https://user-images.githubusercontent.com/52940678/197478110-bd44d38e-ad53-446f-a5f0-6746c005521b.png)

**Comment by SailM23** [comment]
To ease the usage of the reference tools, there is no need to add the datasource and create dashboard in Grafana. We have provided the pre-configured automated dashboards for both InfluxDB as well as prometheus to visualize the telemetry data. Details are in the whitepaper and YouTube video at below links:
https://dl.dell.com/content/manual3687441-idrac9-telemetry-reference-tools-data-visualization.pdf?language=en-us
https://www.youtube.com/watch?v=EBpBKBEidq8

Other than pre-configured automated dashboards, new configuration could be done by adding the datasources and the resolution for the above 'InfluxDB Error: Bad Request' error is with User:admin and Password:'token shown by DOCKER_INFLUXDB_INIT_ADMIN_TOKEN'

 cat iDRAC-Telemetry-Reference-Tools/.env
USER_ID=2005
GROUP_ID=2005
DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=5fcb190e-f129-4430-8a2f-28d6e0bf8165
...

**Comment by SailM23** [comment]
If the above works for you, this ticket could be closed.

**Comment by huazhou007** [comment]
I try this  but this error again,could you help my teams or email is  hua_zhou1@dell.com
![image](https://user-images.githubusercontent.com/52940678/197538694-8224aa56-62ad-41b3-80ff-6bda3e2caf51.png)

![image](https://user-images.githubusercontent.com/52940678/197538815-5b071df2-075d-4ce5-bb58-aaa38d47bc9a.png)
![image](https://user-images.githubusercontent.com/52940678/197538867-884c77cc-dfe2-4836-9a78-05956d7135dd.png)
![image](https://user-images.githubusercontent.com/52940678/197538902-550a90f2-66f4-43d1-b7c2-9bb919af8765.png)

**Comment by SailM23** [comment]
Had a call with @huazhou007 and provided pointers. Datasource got added successfully (using DOCKER_INFLUXDB_INIT_ADMIN_TOKEN) and 3 buckets seen, above issue with datsource is resolved. But there is no data in the dashboards because time of idrac is not in sync with time of the reference tools. idrac time future somewhere around 19:05 and docker tools ~2pm. Time needs to be fixed to see the data in the automated dashboards/configured dashboards.

**Comment by SailM23** [comment]
I chat with @huazhou007 and helped with seeing the data in automated dashboards (powermetrics) and also add the influxdb in the grafana datasource, successfully added 3 buckets. This ticket can be closed and open others if stuck with any other issue.

**Comment by huazhou007** [comment]
@SailM23    You are very patience，Thanks a lot!
