### ISSUE TITLE
EnableOrDisableAllTelemetryReports.py  not enabling all pre-canned reports

### ISSUE THREAD

**Issue by garasankara** [dell/iDRAC-Telemetry-Reference-Tools#110]
[EnableOrDisableAllTelemetryReports.py](https://github.com/dell/iDRAC-Telemetry-Scripting/blob/master/ConfigurationScripts/EnableOrDisableAllTelemetryReports.py  needs to be fixed... It is only doing AR based settings to enable reports. It should patch using DMTF method, New reports like MemoryMetrics and SFPTransceievr are not in AR so they will be missed

**Comment by windsparks33** [comment]
Fixed with https://github.com/dell/iDRAC-Telemetry-Scripting/pull/11
