### ISSUE TITLE
Splunk containers use significant storage usage over time.

### ISSUE THREAD

**Issue by garasankara** [dell/iDRAC-Telemetry-Reference-Tools#112]
After running for 4 days, looks like splunkpump is using a lot of storage which seems to be the cause of the problem and crash/

**Comment by garasankara** [comment]
![sp-storage](https://user-images.githubusercontent.com/39961355/207939588-2d2f943c-69f5-4590-a563-8e63d2b8895a.PNG)

**Comment by SailM23** [comment]
This issue is reported by Chan Thomas with the below setup: 
deployment of Reference tools with 3 indexers, with 8 idracs streaming in data to Splunk on one node and 2 other nodes(one with search head and other with manager). After running for about 4 days, the crash happens with the docker containers and the storage reported by Splunk container looks to be high, as in the above image.

**Comment by SailM23** [comment]
splunkpump has logs which could be removed, might be the reason for filling up the storage:
 ls -lrt /var/lib/docker/containers/b2eb4dd36884fc997d3ae7cc5ea951ae80b52a43f8e1267b6c05b73659d98b4f/
total 13214744
drwx------ 2 root root           6 Dec 12 18:44 checkpoints
-rw-r--r-- 1 root root          71 Dec 12 18:44 resolv.conf.hash
-rw-r--r-- 1 root root         174 Dec 12 18:44 hosts
drwx--x--- 2 root root           6 Dec 12 18:44 mounts
-rw-r--r-- 1 root root          13 Dec 12 18:44 hostname
-rw-r--r-- 1 root root          38 Dec 12 18:44 resolv.conf
-rw-r--r-- 1 root root        1516 Dec 12 18:44 hostconfig.json
-rw------- 1 root root        3617 Dec 12 18:44 config.v2.json
-rw-r----- 1 root root **13057692330** Dec 15 15:44 b2eb4dd36884fc997d3ae7cc5ea951ae80b52a43f8e1267b6c05b73659d98b4f-json.log


 du -hd1 /var/lib/docker/containers/
32K     /var/lib/docker/containers/fbe5766a44a77e1c823d884aaaa3cc98201b4481c82b0d335dc4baf066925f9d
40K     /var/lib/docker/containers/5cdc0132e15765da6f7dbc845b04d771ed9311f1b134d242aedaa01115ed26b2
**13G     /var/lib/docker/containers/b2eb4dd36884fc997d3ae7cc5ea951ae80b52a43f8e1267b6c05b73659d98b4f**
32K     /var/lib/docker/containers/8cf65057cc4bab06416439b817925b9d51eeb370378311e66398f486b01caf7c
28K     /var/lib/docker/containers/00941eddcd0cb2a23df0595a48ffd6dc0d39c2c977541271b74b89d812f8e5a9
112M    /var/lib/docker/containers/f9b87a80d1499718d750c90ad5321ad40537ab643df3f820ab4d5cd3e97e0bd9
13G     /var/lib/docker/containers/
[root@localhost ~]# docker ps -a
CONTAINER ID   IMAGE                                                COMMAND                  CREATED      STATUS      PORTS                                                                                       NAMES
8cf65057cc4b   idrac-telemetry-reference-tools/configui:latest      "/app"                   2 days ago   Up 2 days   0.0.0.0:8080->8082/tcp, :::8080->8082/tcp                                                   idrac-telemetry-reference-tools-configui-1
00941eddcd0c   idrac-telemetry-reference-tools/dbdiscauth:latest    "/app"                   2 days ago   Up 2 days                                                                                               idrac-telemetry-reference-tools-dbdiscauth-1
f9b87a80d149   idrac-telemetry-reference-tools/redfishread:latest   "/app"                   2 days ago   Up 2 days                                                                                               idrac-telemetry-reference-tools-redfishread-1
**b2eb4dd36884**   idrac-telemetry-reference-tools/**splunkpump**:latest    "/app"                   2 days ago   Up 2 days                                                                                               idrac-telemetry-reference-tools-splunk-pump-standalone-1
5cdc0132e157   mysql:latest                                         "docker-entrypoint.s…"   2 days ago   Up 2 days   3306/tcp, 33060/tcp                                                                         mysqldb
fbe5766a44a7   rmohr/activemq:latest                                "/bin/sh -c 'bin/act…"   2 days ago   Up 2 days   1883/tcp, 5672/tcp, 61613-61614/tcp, 61616/tcp, 0.0.0.0:8161->8161/tcp, :::8161->8161/tcp   activemq

**Comment by SailM23** [comment]
Splunkpump consumption is 13G after running for 2 days, and these splunkpump logs could be commented:

 tail -F  /var/lib/docker/containers/b2eb4dd36884fc997d3ae7cc5ea951ae80b52a43f8e1267b6c05b73659d98b4f/b2eb4dd36884fc997d3ae7cc5ea951ae80b52a43f8e1267b6c05b73659d98b4f-json.log
{"log":"2022/12/15 21:47:25 Timestamp = 1671140782 ID = Disk 14 in Backplane 1 of RAID Controller in SL 3_TemperatureReading System = 6B3MK93\n","stream":"stderr","time":"2022-12-15T21:47:25.296488276Z"}
{"log":"2022/12/15 21:47:25 Timestamp = 1671140782 ID = Disk 9 in Backplane 1 of RAID Controller in SL 3_TemperatureReading System = 6B3MK93\n","stream":"stderr","time":"2022-12-15T21:47:25.296492082Z"}
{"log":"2022/12/15 21:47:25 Timestamp = 1671140782 ID = Disk 10 in Backplane 1 of RAID Controller in SL 3_TemperatureReading System = 6B3MK93\n","stream":"stderr","time":"2022-12-15T21:47:25.296717503Z"}
{"log":"2022/12/15 21:47:25 Timestamp = 1671140782 ID = Disk 5 in Backplane 1 of RAID Controller in SL 3_TemperatureReading System = 6B3MK93\n","stream":"stderr","time":"2022-12-15T21:47:25.296721928Z"}
{"log":"2022/12/15 21:47:25 Timestamp = 1671140782 ID = Disk 12 in Backplane 1 of RAID Controller in SL 3_TemperatureReading System = 6B3MK93\n","stream":"stderr","time":"2022-12-15T21:47:25.296755205Z"}
{"log":"2022/12/15 21:47:25 Timestamp = 1671140782 ID = Disk 15 in Backplane 1 of RAID Controller in SL 3_TemperatureReading System = 6B3MK93\n","stream":"stderr","time":"2022-12-15T21:47:25.296760391Z"}
{"log":"2022/12/15 21:47:25 Timestamp = 1671140782 ID = Disk 4 in Backplane 1 of RAID Controller in SL 3_TemperatureReading System = 6B3MK93\n","stream":"stderr","time":"2022-12-15T21:47:25.296764289Z"}
{"log":"2022/12/15 21:47:25 Timestamp = 1671140782 ID = Disk 3 in Backplane 1 of RAID Controller in SL 3_TemperatureReading System = 6B3MK93\n","stream":"stderr","time":"2022-12-15T21:47:25.296768587Z"}
{"log":"2022/12/15 21:47:25 Timestamp = 1671140782 ID = Disk 11 in Backplane 1 of RAID Controller in SL 3_TemperatureReading System = 6B3MK93\n","stream":"stderr","time":"2022-12-15T21:47:25.296772547Z"}
{"log":"2022/12/15 21:47:25 Sent to Splunk. Got back 200\n","stream":"stderr","time":"2022-12-15T21:47:25.29811022Z"}
{"log":"2022/12/15 21:47:27 Timestamp = 1671140840 ID = CPU2 Temp_TemperatureReading System = B049K93\n","stream":"stderr","time":"2022-12-15T21:47:27.713298772Z"}
{"log":"2022/12/15 21:47:27 Timestamp = 1671140838 ID = CPU1 Temp_TemperatureReading System = B049K93\n","stream":"stderr","time":"2022-12-15T21:47:27.713484921Z"}
{"log":"2022/12/15 21:47:27 Timestamp = 1671140835 ID = CPU2 Temp_TemperatureReading System = B049K93\n","stream":"stderr","time":"2022-12-15T21:47:27.71350565Z"}
{"log":"2022/12/15 21:47:27 Timestamp = 1671140834 ID = CPU1 Temp_TemperatureReading System = B049K93\n","stream":"stderr","time":"2022-12-15T21:47:27.713514093Z"}

func logToSplunk(events []*SplunkEvent) {
	var builder strings.Builder
	for _, event := range events {
		b, _ := json.Marshal(event)
		builder.Write(b)
		**log.Printf("Timestamp = %d ID = %s System = %s", event.Time, event.Fields.MetricName, event.Host)**
	}
