### ISSUE TITLE
Sometimes idracs not getting added in the add service of the ConfigUI

### ISSUE THREAD

**Issue by SailM23** [dell/iDRAC-Telemetry-Reference-Tools#113]
Sometimes idracs not getting added in the add service of the ConfigUI. Seen with both addService and add CSV

**Comment by ronbassett** [comment]
Hi @SailM23 can you confirm this is fixed or no longer a problem for you?

**Comment by SailM23** [comment]
didnt really verify as i moved out of the iDRAC org, closing it.
