### ISSUE TITLE
Unable to run compose.sh with docker compose plugin

### ISSUE THREAD

**Issue by Rouzax** [dell/iDRAC-Telemetry-Reference-Tools#119]
Have set up a server with Docker and the Compose plugin.
Running the `compose.sh` gives me this error.
```bash
user@telemetry:/usr/local/idrac_telemetry/docker-compose-files$ ./compose.sh --influx-pump --influx-test-db
./compose.sh: line 179: docker-compose: command not found
./compose.sh: line 38: ((: 10#2 > 10#: invalid integer constant (error token is "10#")
./compose.sh: line 42: ((: 10#2 < 10#: invalid integer constant (error token is "10#")
FAIL: Your docker compose version is 2.2.0. It must be 2.2.0 or higher!
```

Running the command from the script `docker-compose --version` gives an error since the Compose Plugin expects
`docker-compose version`
That results in `Docker Compose version v2.16.0`

**Comment by garasankara** [comment]
Please make sure docker-compose is in your PATH to find. It is usually symlink to actual docker-compose binary , say docker-compose-v2.16.0.   /usr/local/bin/docker-compose -> docker-compose-v2.16.0.  Add /usr/local/bin your PATH

**Comment by garasankara** [comment]
Please let us know if we can close the issue. This is only setup issue, not compose.sh script issue.

**Comment by garasankara** [comment]
This is only setup issue, not compose.sh script issue. User error.
