### ISSUE TITLE
bash ./docker-compose-files/compose.sh --splunk-pump start

### ISSUE THREAD

**Issue by xutao123777** [dell/iDRAC-Telemetry-Reference-Tools#120]
bash ./docker-compose-files/compose.sh --splunk-pump start
Pass: Docker compose version is 2.17.2.
prometheus variable is: 
Set up environment file in /data/iDRAC-Telemetry-Reference-Tools/.env
To run manually, run the following command line:
docker-compose --project-directory /data/iDRAC-Telemetry-Reference-Tools -f /data/iDRAC-Telemetry-Reference-Tools/docker-compose-files/docker-compose.yml --profile core --profile splunk-pump up  -d

yaml: unmarshal errors:
  line 177: mapping key "<<" already defined at line 176
  line 188: mapping key "<<" already defined at line 187
  line 236: mapping key "<<" already defined at line 235
  line 313: mapping key "<<" already defined at line 312
  line 364: mapping key "<<" already defined at line 363
  line 365: mapping key "<<" already defined at line 363
  line 365: mapping key "<<" already defined at line 364
  line 386: mapping key "<<" already defined at line 385
  line 387: mapping key "<<" already defined at line 385
  line 388: mapping key "<<" already defined at line 385
  line 389: mapping key "<<" already defined at line 385
  line 387: mapping key "<<" already defined at line 386
  line 388: mapping key "<<" already defined at line 386
  line 389: mapping key "<<" already defined at line 386
  line 388: mapping key "<<" already defined at line 387
  line 389: mapping key "<<" already defined at line 387
  line 389: mapping key "<<" already defined at line 388
  line 502: mapping key "<<" already defined at line 501

**Comment by y-yas** [comment]
The same error occurred in my environment.

**Comment by TrevorSquillario** [comment]
Same here. 

```
Pass: Docker compose version is 2.20.2.
prometheus variable is:
Set up environment file in /home/trevor/git/iDRAC-Telemetry-Reference-Tools/.env
To run manually, run the following command line:
docker-compose --project-directory /home/trevor/git/iDRAC-Telemetry-Reference-Tools -f /home/trevor/git/iDRAC-Telemetry-Reference-Tools/docker-compose-files/docker-compose.yml --profile core --profile kafka-pump up  -d

parsing /home/trevor/git/iDRAC-Telemetry-Reference-Tools/docker-compose-files/docker-compose.yml: yaml: unmarshal errors:
  line 178: mapping key "<<" already defined at line 177
  line 189: mapping key "<<" already defined at line 188
  line 237: mapping key "<<" already defined at line 236
  line 314: mapping key "<<" already defined at line 313
  line 365: mapping key "<<" already defined at line 364
  line 366: mapping key "<<" already defined at line 364
  line 366: mapping key "<<" already defined at line 365
  line 387: mapping key "<<" already defined at line 386
  line 388: mapping key "<<" already defined at line 386
  line 389: mapping key "<<" already defined at line 386
  line 390: mapping key "<<" already defined at line 386
  line 388: mapping key "<<" already defined at line 387
  line 389: mapping key "<<" already defined at line 387
  line 390: mapping key "<<" already defined at line 387
  line 389: mapping key "<<" already defined at line 388
  line 390: mapping key "<<" already defined at line 388
  line 390: mapping key "<<" already defined at line 389
  line 503: mapping key "<<" already defined at line 502

```
