### ISSUE TITLE
/cmd/timescalepump/initialize_timescaledb mandating to use the default user "postgres" which is causing authentication failure for other users

### ISSUE THREAD

**Issue by nethramg** [dell/iDRAC-Telemetry-Reference-Tools#145]
Omnia wants to upgrade iDRAC tools to the latest commit id  [dell/iDRAC-Telemetry-Reference-Tools at 301212c80581cf9d3d97b074b28d908373cb08f9 (github.com)](https://github.com/dell/iDRAC-Telemetry-Reference-Tools/tree/301212c80581cf9d3d97b074b28d908373cb08f9).

Observations with IDRAC tools commit id "301212c" when compared to commit id "0016fcb"
The latest initialize_timescaledb.sh path is changed to /cmd/timescalepump/initialize_timescaledb and also mandates to provide the username as postgres. 
Why this username restriction change was made? Can we have any username other name postgres. Please confirm.
![image](https://github.com/user-attachments/assets/43353b02-c9b9-4049-b719-8f0d7e74d83a)

If we provide any other username other than postgres, timescale DB creation fails with the following error.

![image](https://github.com/user-attachments/assets/1207efe2-33af-47b0-9368-d23f8bfd26a7)

**Comment by krishnakartik1** [comment]
@nethramg You can now use any username for the timescale database.
