### ISSUE TITLE
config.ini file has readable iDRAC Password

### ISSUE THREAD

**Issue by sujit-jadhav** [dell/iDRAC-Telemetry-Reference-Tools#15]
config.ini stores the iDRAC Password in readable format. This is security issue.

It is fine to accept the password in readable format but when the Telemetry containers starts this file should be no longer exists in readable format. Telemetry container should convert this file in some encrypted form or take password in encrypted form inside the container and then delete this file.

Later when user wants to make changes in password or add new nodes then user should supply new config.ini file and restart the telemetry container.  

Can you please consider this issue on priority? Omnia HLD itself will not get clearance if this vulnerability is open.

**Comment by SailM23** [comment]
Not an issue, closing for now with the below correspondence:
"
We support more than one method to store password.
Simple config based – This is to enable quick marketing demo and support simplest usecases.
Db based config – authenticated mysql db based store for user credentials.
"

**Comment by sujit-jadhav** [comment]
Since there is alternate way to store the password, I am closing this issue.

**Comment by sujit-jadhav** [comment]
Since there is alternate way to store the password, I am closing this issue.
