### ISSUE TITLE
Command line to use ConfigurationScripts to add subscription for telemetry report missing params

### ISSUE THREAD

**Issue by pradeepar** [dell/iDRAC-Telemetry-Reference-Tools#2]
step 3 in docker-compose-files/setup_guide.pdf to create subscription is missing few params needed to execute correctly 
python3 ./ConfigurationScripts/SubscriptionManagementREDFISH.py -ip $target -u $user -p $password -c y

It requires -D -E and -V params to be added as noted in the help

![image](https://user-images.githubusercontent.com/7271680/115046664-58dd3400-9ef5-11eb-8426-64cb12a75bd9.png)

<img width="516" alt="scriptsnip" src="https://user-images.githubusercontent.com/7271680/115046864-92ae3a80-9ef5-11eb-90db-468f88c22e54.PNG">

**Comment by cjmadathil** [comment]
Addressed with 70e88197f164ff71f6fbe03d41838da8f7f6bf49. 
It was found that execution of SubscriptionManagementREDFISH.py was redundant.
