### ISSUE TITLE
Duplicate key in influx-docker-pipeline-reference-unenc.yml

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Telemetry-Reference-Tools#20]
Haven't tested but I believe this should be a list instead of a duplicated key:

![image](https://user-images.githubusercontent.com/35169230/151869316-d44a2950-3834-48db-a4f2-4eed0b72703b.png)

**Comment by SailM23** [comment]
fixed with merge #25

**Comment by cjmadathil** [comment]
Converted as list - https://github.com/dell/iDRAC-Telemetry-Reference-Tools/pull/25
