### ISSUE TITLE
elkpump will not retry if Elasticsearch doesn't come up

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Telemetry-Reference-Tools#21]
In my instance I didn't set all of the required elasticsearch settings (ex vm.max_map_count) so Elasticsearch failed to start. When this happened elkpump's DNS lookup failed and the container stopped:

```
go: downloading github.com/go-stomp/stomp v2.0.3+incompatible
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/elastic/go-elasticsearch/v8 v8.0.0-20201229214741-2366c2514674
2022/02/02 02:11:19 Cannot delete index: dial tcp: lookup es01: Temporary failure in name resolution
exit status 1
```

Desired behavior should be that it continues to retry until ES is up

**Comment by SailM23** [comment]
PR in the process
