### ISSUE TITLE
Test scripts page in contributor agreement is missing

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Telemetry-Reference-Tools#24]
https://github.com/dell/iDRAC-Telemetry-Reference-Tools/blob/master/tests

The link to the test scripts in the [contributor agreement](https://github.com/dell/iDRAC-Telemetry-Reference-Tools/blob/master/CONTRIBUTING.md) is broken.

**Comment by garasankara** [comment]
Will look into this...

**Comment by krishnakartik1** [comment]
The contributor agreement link referenced above is broken and moved to a different location - [CONTRIBUTING.md](https://github.com/dell/iDRAC-Telemetry-Reference-Tools/blob/main/docs/CONTRIBUTING.md)

The new document no longer has any references to the test scripts. This issue can be closed.
