### ISSUE TITLE
Because files are mounted, mounting from a filesystem using CRLF will cause failures

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Telemetry-Reference-Tools#27]
```bash
root@e0f6acee0d14:/go/src/github.com/telemetry-reference-tools# cmd/idrac-telemetry-receiver.sh
cmd/idrac-telemetry-receiver.sh: line 1: $'\r': command not found
cmd/idrac-telemetry-receiver.sh: line 2: $'\r': command not found
cmd/idrac-telemetry-receiver.sh: line 3: $'\r': command not found
```

In my case I was deving from Windows sync'd to a remote Linux system. Because the code is mounted instead of being container-native, if the saved format converts line endings to CRLF the code fails.

We should ensure that git saves all files with Unix-style line endings.

If we choose to include a startup script it should check that all required files use only LF instead of CRLF

**Comment by windsparks33** [comment]
I'll start taking a look.

**Comment by grantcurell** [comment]
Eh I'm going to close this one. Now that I look back at it - it is a problem, but it's more of a problem with my dev environment. not worth burning time on

**Comment by windsparks33** [comment]
Thanks Grant
