### ISSUE TITLE
configgui does not expose any ports

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Telemetry-Reference-Tools#28]
The telemetry-receiver container which runs configgui, does not expose any ports so there is no way to connect to it.

Temporary solution: expose a fixed port
Permanent solution: Many of the variables inside the docker compose file are configurable. There will need to be an external config file or something combined with a jinja2 template. OR you would have to have something which will update these values live.

It would probably be best if some central template engine controlled everything because additionally the user may turn things off and in in the telemetry receiver file which would further change what ports should and should not be open. This could all be done with Jinja. In a more sophisticated scenario Ansible

**Comment by SailM23** [comment]
telemetry-receiver is initial version of the UI to configure the idrac feeding in the metric reports to Reference tool-set. we have plans to take this further enhance with more options to configure and better look. May take this as enhancement, as no functional issue.

**Comment by grantcurell** [comment]
[deleted old message] sorry got turned around on issues and thought this was for the passwords

**Comment by windsparks33** [comment]
Hi, I was assigned to work on this, I'll take a look today.

**Comment by grantcurell** [comment]
@windsparks33 heads up, this will be fixed with https://github.com/superchalupa/iDRAC-Telemetry-Reference-Tools/pull/1 (when Mike then pulls it into this repo). No further action required on this ticket
