### ISSUE TITLE
configgui logs password to STDOUT in plaintext

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Telemetry-Reference-Tools#29]
![image](https://user-images.githubusercontent.com/35169230/153046274-282f7245-14ac-4c07-b721-2e66afe7cc59.png)

Configgui is a cool tool and I like the bootstrap interface but it looks like it logs all received system passwords in plaintext. This is retrievable with `docker logs telemetry-receiver`. This should be changed moving forward

**Comment by SailM23** [comment]
Sent PR [Removing the printing of password from telemetryservice UI](https://github.com/dell/iDRAC-Telemetry-Reference-Tools/pull/32)
#32 opened 2 minutes ago by [SailM23](https://github.com/dell/iDRAC-Telemetry-Reference-Tools/issues?q=is%3Apr+is%3Aopen+author%3ASailM23)
