### ISSUE TITLE
Redfish telemetry service configuration(UI) needs to have the service added twice, to reflect

### ISSUE THREAD

**Issue by SailM23** [dell/iDRAC-Telemetry-Reference-Tools#3]
Redfish telemetry service configuration(UI) needs to have the service added twice, to reflect

**Comment by SailM23** [comment]
fixed on code push done on 11/9/2021.

**Comment by cjmadathil** [comment]
Fix seems not appropriate. Two instances of dbauth app have to run and file based discovery is not included.

**Comment by SailM23** [comment]
Enhancement,  working on it.

**Comment by SailM23** [comment]
This issue is no longer seen with the compose.sh
