### ISSUE TITLE
The configuration service prints the root password when reading from mysql

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Telemetry-Reference-Tools#34]
![image](https://user-images.githubusercontent.com/35169230/155539371-eeae7aca-92ef-483d-92a9-a7311caae200.png)

**Comment by SailM23** [comment]
this was fixed. Did you update your codebase?

**Comment by grantcurell** [comment]
Yes - codebase updated.

Same type of problem - different place. I haven't tracked down where it is happening but it looks like when the data is read back out of mysql it also prints it to screen
