### ISSUE TITLE
Sensitive info in logs

### ISSUE THREAD

**Issue by superchalupa** [dell/iDRAC-Telemetry-Reference-Tools#44]
dbdiscauth and influx-pump both log tokens or passwords.

**Comment by SailM23** [comment]
i fixed in few of the places earlier, will check if these are not fixed.

**Comment by superchalupa** [comment]
Fixes https://github.com/dell/iDRAC-Telemetry-Reference-Tools/pull/45

**Comment by windsparks33** [comment]
looks to be fixed by issue by superchalupa's fix.
