### ISSUE TITLE
Docker compose throws erroneous errors confusing the user

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Telemetry-Reference-Tools#46]
When running the build several containers error. These errors are safe to ignore but we should clear them.

![image](https://user-images.githubusercontent.com/35169230/156659084-e21d62e6-8f77-47c2-b564-1e03a61bc20f.png)

**Comment by superchalupa** [comment]
I was able to confirm those errors locally. I am not sure how or where they come from?

**Comment by krishnakartik1** [comment]
These errors don't show up anymore. Tested all the pumps using docker-compose version v2.16.0. Closing the issue.
