### ISSUE TITLE
Update the upload file service to properly check for completion

### ISSUE THREAD

**Issue by grantcurell** [dell/iDRAC-Telemetry-Reference-Tools#47]
Because I am bad at web dev and it is getting late I did this:

```javascript
    async function uploadFile() {
        let formData = new FormData();
        formData.append("file", fileupload.files[0]);
        await fetch('/api/v1/CsvUpload', {
            method: "POST",
            body: formData,
            contentType: 'text/csv'
        });
        alert("CSV file processing completed. Refresh the page to confirm the services were added. Check logs for " +
            "results.")
        $('#csvModal').modal('toggle');
    }
```

It is bad. I know it is bad. It ought be fixed, but I need it working for tomorrow and it currently works. This should be updated to check if there were any errors in the file upload.

**Comment by superchalupa** [comment]
seems good enough to me? Submit a PR.

Does it need a new button or something?

**Comment by garasankara** [comment]
https://github.com/dell/iDRAC-Telemetry-Reference-Tools/pull/128 fixed the issue.
