### ISSUE TITLE
Elastic Pipeline missing documents 

### ISSUE THREAD

**Issue by 00-eight** [dell/iDRAC-Telemetry-Reference-Tools#55]
When using the docker-compose elk reference pipeline there are gaps between sensor readings. 
![kibana_db_gaps](https://user-images.githubusercontent.com/33444085/158449430-ad39704e-ccc3-4043-92f9-aab42380dd28.png)
Viewing Aggregation from ES it is clear that documents are missing from these sensors. 
```
  "aggregations": {
    "by_context": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "CPU2 Temp",
          "doc_count": 13520
        },
        {
          "key": "CPU1 Temp",
          "doc_count": 8088
        }
      ]
    }
  }
```
When viewing a parallel SSE from iDRAC it is clear all readings are present. 
When viewing es-ingester logs it is clear that all readings are being read from databus 
```
/* https://github.com/dell/iDRAC-Telemetry-Reference-Tools/blob/main/cmd/elkpump-basic/elkpump-basic.go */
			log.Print("value: ", value) // line 80 
```
I suspect that these readings are getting lost during handleGroups call to [esapi.bulk](https://github.com/elastic/go-elasticsearch/blob/main/esapi/api.bulk.go)

Corresponding es-ingester logs and ES aggregation for dashboard image 
[es-ingester_and_kibana_agg.log](https://github.com/dell/iDRAC-Telemetry-Reference-Tools/files/8256351/es-ingester_and_kibana_agg.log)

**Comment by SailM23** [comment]
Thanks for opening this ticket, will look into the issue and get back...

**Comment by SailM23** [comment]
This is issue is closed as the data discrepancy between the Fan1,Fan2 etc of idrac SSE is accumulated and showing as big difference in the doc_count of the sql query in the Kibana. More details in the Jit story TLM-573.
