### ISSUE TITLE
prometheus-ingester is not known host

### ISSUE THREAD

**Issue by ajya** [dell/iDRAC-Telemetry-Reference-Tools#56]
Installing Prometheus pump results in `prometheus-ingester` target down as defined at `cmd/prometheuspump/prometheus.yml` and as such no data loaded.

Error at Prometheus `/targets`:

> Get http://prometheus-ingester:2112/metrics: dial tcp: lookup prometheus-ingester on 127.0.0.11:53: server misbehaving

Prometheus pump container has alias `prometheus-pump-withtestserver` or `prometheus-pump-standalone` depending on test db being used or not.

`prometheus-ingester` does not seem to be defined anywhere.

Not sure what was intended, but one way to get around this is to add alias to `prometheus-pump-standalone: &prometheus-pump` at `docker-compose-files/docker-compose.yml`:
```
    networks:
      host-bridge-net:
        aliases:
          - prometheus-ingester
```	  
As long as both `prometheus-pump-standalone`, `prometheus-pump-withtestserver` are not running sharing the same alias this should be fine, but maybe there is better solution.

**Comment by grantcurell** [comment]
Hey @ajya - apologies, just doing some prioritization. Are you on the customer side or the Dell side?

**Comment by grantcurell** [comment]
Nvm, I'm guessing the Dell side since I can assign you to the ticket 😂

Are you using this Dell internal? We're trying to get a better feel for how the reference framework is being consumed so we can figure out what features are most in demand/in use. Feel free to hit me up internal if you like
