### ISSUE TITLE
sdk splunk app is having restart issues

### ISSUE THREAD

**Issue by windsparks33** [dell/iDRAC-Telemetry-Reference-Tools#69]
The issue ticket is created to track
-> sdk splunk application restart issues
-> sdk splunk application usage documentation add to github.

https://github.com/dell/iDRAC-Telemetry-Reference-Tools/tree/main/cmd/idracsdkapps/splunkapp

**Comment by krishnakartik1** [comment]
Moved to internal repo

**Comment by krishnakartik1** [comment]
Moved to internal repo
