### ISSUE TITLE
elk-pump workflow does not start

### ISSUE THREAD

**Issue by windsparks33** [dell/iDRAC-Telemetry-Reference-Tools#82]

**Comment by SailM23** [comment]
for notes, these are the errors seen while establishing the elkstack client connection:

telemetry@Ubuntu1804-01:/mnt/sda/InfluxSetupSeparate/iDRAC-Telemetry-Reference-Tools$ docker logs --follow 7136707f86c2
2022/07/25 22:59:48 Could not connect to message bus: dial tcp 172.19.0.5:61613: connect: connection refused
2022/07/25 22:59:53 Could not connect to message bus: dial tcp 172.19.0.5:61613: connect: connection refused
2022/07/25 22:59:58 connected to message bus
2022/07/25 23:00:13 Elasticsearch client is initialized & print esInfo
2022/07/25 23:00:14 **[0 <nil>]** dial tcp: i/o timeout
2022/07/25 23:00:29 **Cannot create index: dial tcp: i/o timeout**

**Comment by windsparks33** [comment]
Fixed with https://github.com/dell/iDRAC-Telemetry-Reference-Tools/pull/106
